# Introduction to R Programming Basic To Advance
**R** is a programming language .
<br>It is free and can be downloaded from intenet:
   http://cran.r-project.org.
<br>It doesn"t require internet .
<br>It’s has very powerful graphics capabilities *(ggplot2)*.
<br>It’s has a large no. of libraries and packages.
<br> It’s widely use for **Statistics , Data Science , Data Ananlysis  Machine Learning , Artificial Intelligence , Deep Learning**
<br>It’s also used as calculator .
## Naming an object in R
Some examples of valid and invalid names are given below:
<br>$\bullet$ a1 is valid
<br>$\bullet$ 1a is not valid as it starts wih numeric
<br>$\bullet$ A12_5 is valid
<br>$\bullet$ ZainlAbedeen is valid
<br>$\bullet$ Zainl Abedeen is not valid as fractured names are not allowed.
<br>$\bullet$ ZainlAbedeen <- 5 is valid
<br>$\bullet$ Zainl_Abedeen <- 5 is valid

# R as Calculator
Anything that can be computed on a pocket calculator can be computed at R prompt.The basic operations are **+ (add), - (subtract), *(multiply) and / (divide)**.

In [6]:
print(paste("a=300 , b=400"))
# To Add
print(paste("Addition of two num=",300+400))
# To Subtract
print(paste("Subtraction of two number=",300-400))
# To Multiplication
print(paste("Multiplication of two number=",300*400))
# To Divide
print(paste("Dividation of two number=",300/400))
print("We can also done it by assigning the vector")
# We can also done it by assigning the vector
a=400  
b=300
print(paste("Addition of two num=",a+b))
print(paste("Subtraction of two number=",a-b))
print(paste("Multiplication of two number=",a*b))
print(paste("Dividation of two number=",a/b))
# To compute the power : a^b OR a ^ b
print(paste("Power of two number=",a^b))
# To compute the Modular : a %% b  OR a%%b
print(paste("Modular of two number=",a %% b))
# To compute the Integer : a %/% b # OR a%/%b
print(paste("Integer of two number=",a %/% b))

[1] "a=300 , b=400"
[1] "Addition of two num= 700"
[1] "Subtraction of two number= -100"
[1] "Multiplication of two number= 120000"
[1] "Dividation of two number= 0.75"
[1] "We can also done it by assigning the vector"
[1] "Addition of two num= 700"
[1] "Subtraction of two number= 100"
[1] "Multiplication of two number= 120000"
[1] "Dividation of two number= 1.33333333333333"
[1] "Power of two number= Inf"
[1] "Modular of two number= 100"
[1] "Integer of two number= 1"


## Creating a Vector – c() & Arithmetic Operations on Vectors
If we want to assign more than one value than we write it as **C($x_1,x_2,......,x_n$)**, where c is combine

In [8]:
# Let us define a vector x as
x=c(5,4,3,1,4) # define x vector
x

[1] 5 4 3 1 4

In [9]:
length(x) # length of x / No. of elements in x

[1] 5

In [10]:
sum(x) # sum of elements

[1] 17

In [11]:
sum(x^2) # sum of squares

[1] 67

In [12]:
sqrt(x) # square root of x

[1] 2.236068 2.000000 1.732051 1.000000 2.000000

In [13]:
log(x) # log of x with base e

[1] 1.609438 1.386294 1.098612 0.000000 1.386294

In [14]:
log(x, base=10)# log of x with 10

[1] 0.6989700 0.6020600 0.4771213 0.0000000 0.6020600

In [15]:
log(x, base=5) # log of x with 5

[1] 1.0000000 0.8613531 0.6826062 0.0000000 0.8613531

In [16]:
1/x # inverse of x

[1] 0.2000000 0.2500000 0.3333333 1.0000000 0.2500000

In [17]:
x^-1 # same as above

[1] 0.2000000 0.2500000 0.3333333 1.0000000 0.2500000

In [18]:
sin(x) # sin of x

[1] -0.9589243 -0.7568025  0.1411200  0.8414710 -0.7568025

In [19]:
cos(x) # cos of x

[1]  0.2836622 -0.6536436 -0.9899925  0.5403023 -0.6536436

In [20]:
tan(x) # tan of x

[1] -3.3805150  1.1578213 -0.1425465  1.5574077  1.1578213

In [21]:
mean(x) # mean of x

[1] 3.4

In [22]:
var(x) # variance of x

[1] 2.3

In [23]:
# variance using function 1
sum((x-mean(x))^2) / (length(x)-1) 

[1] 2.3

In [24]:
#  variance using function 2
(sum(x^2) - (length(x)*mean(x)^2)) /(length(x)-1) 

[1] 2.3

In [25]:
sd(x) # standard deviation of x

[1] 1.516575

In [26]:
# 1 will recycle up to the length of x andd add
x+1 

[1] 6 5 4 2 5

In [27]:
# Multiply each element of x by 2
2*x 

[1] 10  8  6  2  8

In [28]:
# Log of x+1
log(x+1)

[1] 1.7917595 1.6094379 1.3862944 0.6931472 1.6094379

In [29]:
# sin of 2*x
sin(2*x)

[1] -0.5440211  0.9893582 -0.2794155  0.9092974  0.9893582

In [30]:
# Solution of Equation
y=2*x^2+3*x+5
y

[1] 70 49 32 10 49

## Sequencing in R– ‘seq()’
In R we use **seq(a, b, by=?)** function or a:b for sequencing

In [31]:
# sequence from 10 to 20 by 0.5
seq(10, 20,  by=0.5 )

[1] 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 14.5 15.0 15.5 16.0 16.5 17.0
[16] 17.5 18.0 18.5 19.0 19.5 20.0

In [32]:
x1<-seq(from=1,to=30,by=1)
x1

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30

In [33]:
# Reverce Sequence from 30 to 1
rx1=seq(from=30,to=1)
rx1

[1] 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
[26]  5  4  3  2  1

In [34]:
10:20

[1] 10 11 12 13 14 15 16 17 18 19 20

In [35]:
20:10

[1] 20 19 18 17 16 15 14 13 12 11 10

## Repeat any Value in R– rep()
In R we use **rep(c($x_1,x_2$),c($n_1,n_2$))** we repeat the value $x_1 , n_1$ times and  $x_2 , n_2$ times respectively.
<br>In R we write character vectors in double quotoes " "

In [36]:
# repeat 1 3 times and 2 also 3 times
rep(c(1,2),c(3,3)) 

[1] 1 1 1 2 2 2

In [37]:
# Repeat 1 and 2 each 4 times
rep(c(1,2),each=4)

[1] 1 1 1 1 2 2 2 2

In [38]:
rep(c("R1","R2","R3"),c(3,2,4))

[1] "R1" "R1" "R1" "R2" "R2" "R3" "R3" "R3" "R3"

In [39]:
tasbihefatimi=rep(c("SubhanAllah","Alhamadulliah","Allahuakbar"),c(33,33,34))
tasbihefatimi

[1] "SubhanAllah"   "SubhanAllah"   "SubhanAllah"   "SubhanAllah"  
  [5] "SubhanAllah"   "SubhanAllah"   "SubhanAllah"   "SubhanAllah"  
  [9] "SubhanAllah"   "SubhanAllah"   "SubhanAllah"   "SubhanAllah"  
 [13] "SubhanAllah"   "SubhanAllah"   "SubhanAllah"   "SubhanAllah"  
 [17] "SubhanAllah"   "SubhanAllah"   "SubhanAllah"   "SubhanAllah"  
 [21] "SubhanAllah"   "SubhanAllah"   "SubhanAllah"   "SubhanAllah"  
 [25] "SubhanAllah"   "SubhanAllah"   "SubhanAllah"   "SubhanAllah"  
 [29] "SubhanAllah"   "SubhanAllah"   "SubhanAllah"   "SubhanAllah"  
 [33] "SubhanAllah"   "Alhamadulliah" "Alhamadulliah" "Alhamadulliah"
 [37] "Alhamadulliah" "Alhamadulliah" "Alhamadulliah" "Alhamadulliah"
 [41] "Alhamadulliah" "Alhamadulliah" "Alhamadulliah" "Alhamadulliah"
 [45] "Alhamadulliah" "Alhamadulliah" "Alhamadulliah" "Alhamadulliah"
 [49] "Alhamadulliah" "Alhamadulliah" "Alhamadulliah" "Alhamadulliah"
 [53] "Alhamadulliah" "Alhamadulliah" "Alhamadulliah" "Alhamadulliah"
 [57] "Alhamadulliah" "Alhamadulliah" "Alhamadulliah" "Alhamadulliah"
 [61] "Alhamadulliah" "Alhamadulliah" "Alhamadulliah" "Alhamadulliah"
 [65] "Alhamadulliah" "Alhamadulliah" "Allahuakbar"   "Allahuakbar"  
 [69] "Allahuakbar"   "Allahuakbar"   "Allahuakbar"   "Allahuakbar"  
 [73] "Allahuakbar"   "Allahuakbar"   "Allahuakbar"   "Allahuakbar"  
 [77] "Allahuakbar"   "Allahuakbar"   "Allahuakbar"   "Allahuakbar"  
 [81] "Allahuakbar"   "Allahuakbar"   "Allahuakbar"   "Allahuakbar"  
 [85] "Allahuakbar"   "Allahuakbar"   "Allahuakbar"   "Allahuakbar"  
 [89] "Allahuakbar"   "Allahuakbar"   "Allahuakbar"   "Allahuakbar"  
 [93] "Allahuakbar"   "Allahuakbar"   "Allahuakbar"   "Allahuakbar"  
 [97] "Allahuakbar"   "Allahuakbar"   "Allahuakbar"   "Allahuakbar"

## Logical Operator in R– TRUE(1) , FALSE(0)
$$
*  > Greater than (>) 
*  < Less than (<)
*  >= Greater than equal to (>=)
*  <= Less than equal to (<=)
*  == Exactly equal to (==)
*  != Not equal to (!=)
*  | OR Operator (|)
*  & AND Operator (&)
$$

In [40]:
x=c(2,5,3,1,8)
x>3    # x is greater than 3

[1] FALSE  TRUE FALSE FALSE  TRUE

In [41]:
sum(x>3)  # sum of x which is greater than 3

[1] 2

In [43]:
 # Extract the values which are  greater than 2 from the vector x 
(x[x>2]) 

[1] 5 3 8

In [44]:
# mean of the extracted values which are  greater than 2 from the vector x
mean(x[x>2])

[1] 5.333333

In [45]:
# mean of the extracted values which are less than 3 from the vector x 
mean(x[x<3])

[1] 1.5

In [46]:
mean(x<3)  # mean the values which are  greater than 3 from the vector x
## [1] 0.4

[1] 0.4

In [47]:
#logical expression | or, & , and
# logical expression for the values which are greater than 2 & less than 4
x>2 & x<4  

[1] FALSE FALSE  TRUE FALSE FALSE

In [48]:
# Extract the logical expression for the values which are greater than 2 & less than 4  
x[x>2 & x<4]

[1] 3

In [49]:
# logical expression for the values which are greater than 2 OR less than 4
x>2 | x<4

[1] TRUE TRUE TRUE TRUE TRUE

In [50]:
# Exract logical expression for the values which are greater than 2 OR less than 4]
x[x>2 | x<4]

[1] 2 5 3 1 8

## Missing values— NA 
If any value(s) missing in vector , it’s create a error in programme , to resolve this error we use **is.na()** function .

In [51]:
x=c(2,5,3,NA,6)
is.na(x)

[1] FALSE FALSE FALSE  TRUE FALSE

In [52]:
mean(x)

[1] NA

In [53]:
mean(x,na.rm=TRUE)

[1] 4

In [54]:
!is.na(x)

[1]  TRUE  TRUE  TRUE FALSE  TRUE

In [55]:
mean(x[!is.na(x)])

[1] 4

In [56]:
# Not a number, NaN, 0/0, Inf-Inf, Inf/Inf
x=c(0,5,3)
x/x

[1] NaN   1   1

In [57]:
is.na(x/x)

[1]  TRUE FALSE FALSE

## Pasting  & Seperate
Pasting **paste()** & Seperate-- **sep()**

In [58]:
x=c(2,5,8)
x

[1] 2 5 8

In [59]:
names(x)=c("Zainul","Altamash","Wasiq")
x

Zainul Altamash    Wasiq 
       2        5        8

In [60]:
paste(c("Azam","Zuklekha","Ankit"),c(2,5,8),sep=": ")

[1] "Azam: 2"     "Zuklekha: 5" "Ankit: 8"

In [61]:
paste(c("Azam","Zuklekha","Ankit"),c(2,5,8),sep=": ")

[1] "Azam: 2"     "Zuklekha: 5" "Ankit: 8"

In [62]:
dob=c("10/01/93","12/03/93","15/07/94")
dob

[1] "10/01/93" "12/03/93" "15/07/94"

In [64]:
paste0(names(x),dob)

[1] "Zainul10/01/93"   "Altamash12/03/93" "Wasiq15/07/94"

In [65]:
# letters and LETTERS
letters

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [66]:
letters[c(3,6)]

[1] "c" "f"

In [67]:
LETTERS[1:6]

[1] "A" "B" "C" "D" "E" "F"

In [68]:
month.abb

[1] "Jan" "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep" "Oct" "Nov" "Dec"

In [69]:
month.abb[c(3,9)]

[1] "Mar" "Sep"

In [70]:
month.abb[3:9]

[1] "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep"

In [71]:
substr(month.name,1,4)

[1] "Janu" "Febr" "Marc" "Apri" "May"  "June" "July" "Augu" "Sept" "Octo"
[11] "Nove" "Dece"

## Factor vector
**factor() , ordered()**

In [72]:
#Factor is like the
grp=c("control","treatment","control","treatment")
grp

[1] "control"   "treatment" "control"   "treatment"

In [73]:
grp=factor(grp)
as.integer(grp)

[1] 1 2 1 2

In [74]:
as.integer(grp)

[1] 1 2 1 2

In [75]:
levels(grp)

[1] "control"   "treatment"

## Matrix & Array
**matrix()**

In [76]:
m1=c(123,343,343,444,345,665,656,786,342)
m=matrix(m1,nrow = 3) ; m 
# In R by default the observations are fill by column-wise

[,1] [,2] [,3]
[1,] 123  444  656 
[2,] 343  345  786 
[3,] 343  665  342

In [80]:
## If we want to create a matrix which fill by row wise then

r=matrix(m1, byrow = TRUE, nrow = 3) ; r 
cat("Dimension of Matrix -:", dim(r)) 
# To know the dimension of matrix dim()

[,1] [,2] [,3]
[1,] 123  343  343 
[2,] 444  345  665 
[3,] 656  786  342

Dimension of Matrix -: 3 3

In [81]:
# If we want to give the names of rows and columns then
dimnames(r)=list(c("Amroha","Sambhal","Moradabad"),c("Apple","Orange","Litchi"))
r

Apple Orange Litchi
Amroha    123   343    343   
Sambhal   444   345    665   
Moradabad 656   786    342

In [82]:
#Other way
rn=c("Amroha","Sambhal","Moradabad")
cn=c("Apple","Orange","Litchi")
rownames(m)<- rn
colnames(m)<- cn
m

Apple Orange Litchi
Amroha    123   444    656   
Sambhal   343   345    786   
Moradabad 343   665    342

In [83]:
#Another Matrix
a=matrix(1:9,nrow=3)
a

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [84]:
colnames(a)=c("A", "B", "C")
rownames(a)<- c("Amr", "Mbd", "Smb")
a

A B C
Amr 1 4 7
Mbd 2 5 8
Smb 3 6 9

In [85]:
# Extraction from a matrix---- [,]
a[,3]  # for 3rd column

Amr Mbd Smb 
  7   8   9

In [86]:
a[3,] # for 3rd ow

A B C 
3 6 9

In [87]:
a[,c(2,3)]  # for 2nd & 3rd element of each column

B C
Amr 4 7
Mbd 5 8
Smb 6 9

In [89]:
# fo the element which belongs to 3rd row and 2nd column
a[3,2]    

[1] 6

In [93]:
# Arithmetic Operations on Matrix
m2=matrix(1:6,nrow = 2)
m2

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [94]:
# If we want to add any row OR cilumn in a matrix then 
# we use the function "rbind()" for row and 
# "cbind()" for column
x1=c(7,8,9)
m2=rbind(m2,x1)  # To add a row
m2

[,1] [,2] [,3]
   1    3    5   
   2    4    6   
x1 7    8    9

In [95]:
x2=c(7,8,6)
m2=cbind(m2,x2)
m2

x2
   1 3 5 7 
   2 4 6 8 
x1 7 8 9 6

In [96]:
# Arithmetic Operators on a Matrix
a=matrix(1:9, nrow = 3) ; a


[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [97]:
b=matrix(10:18, nrow = 3) ;b

[,1] [,2] [,3]
[1,] 10   13   16  
[2,] 11   14   17  
[3,] 12   15   18

In [98]:
a+b  # To add two Matrices

[,1] [,2] [,3]
[1,] 11   17   23  
[2,] 13   19   25  
[3,] 15   21   27

In [99]:
a-b  # To subtract two Matrices

[,1] [,2] [,3]
[1,] -9   -9   -9  
[2,] -9   -9   -9  
[3,] -9   -9   -9

In [102]:
b-a

[,1] [,2] [,3]
[1,] 9    9    9   
[2,] 9    9    9   
[3,] 9    9    9

In [103]:
a/b # To divide two Matrix

[,1]      [,2]      [,3]     
[1,] 0.1000000 0.3076923 0.4375000
[2,] 0.1818182 0.3571429 0.4705882
[3,] 0.2500000 0.4000000 0.5000000

In [104]:
b/a

[,1] [,2] [,3]    
[1,] 10.0 3.25 2.285714
[2,]  5.5 2.80 2.125000
[3,]  4.0 2.50 2.000000

In [105]:
a*b # Multiplication of Matrix which is really wrong

[,1] [,2] [,3]
[1,] 10   52   112 
[2,] 22   70   136 
[3,] 36   90   162

In [106]:
b*a # Wrong Multiplication

[,1] [,2] [,3]
[1,] 10   52   112 
[2,] 22   70   136 
[3,] 36   90   162

In [107]:
# Both the above multiplication command gives wrong answer
b %*% a

[,1] [,2] [,3]
[1,] 84   201  318 
[2,] 90   216  342 
[3,] 96   231  366

In [108]:
a %*% b

[,1] [,2] [,3]
[1,] 138  174  210 
[2,] 171  216  261 
[3,] 204  258  312

In [113]:
a

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [109]:
1/a # To find reciprocal 

[,1]      [,2]      [,3]     
[1,] 1.0000000 0.2500000 0.1428571
[2,] 0.5000000 0.2000000 0.1250000
[3,] 0.3333333 0.1666667 0.1111111

In [110]:
a+1 # To add 1 in each element of matrix a 

[,1] [,2] [,3]
[1,] 2    5     8  
[2,] 3    6     9  
[3,] 4    7    10

In [111]:
a^2  # for square of each element

[,1] [,2] [,3]
[1,] 1    16   49  
[2,] 4    25   64  
[3,] 9    36   81

In [112]:
t(a) # To transpose the Matrix

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [117]:
# Matrix Solution
#3x1-4x2=6
#x1+2x2=-3
# Ax=b
# x=A(^-1)b
# solve(A,x)
A<-matrix(c(3,1,-4,2),ncol=2)
print( A)

b<-c(6,-3)
print(b)
x=solve(A,b)
print(x)

     [,1] [,2]
[1,]    3   -4
[2,]    1    2
[1]  6 -3
[1] -2.960595e-16 -1.500000e+00


### Array 
Array is multi- dimensional matrix while Matrix is not.
<br>**Note :-** Every Matrix is an Array but every Array is not Matrix .
<br>_**array()**_

In [118]:
a1<- array(1:8,c(2,2,2))
a1
dim(a1)

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

[1] 2 2 2

In [119]:
dimnames(a1)=list(c("a","b"),LETTERS[3:4],c("D1","D2"))
a1

, , D1

  C D
a 1 3
b 2 4

, , D2

  C D
a 5 7
b 6 8

## Data Frame
These are objects, a kind of generalization of matrices . Generalization in the sence that columns can be of different types from each other . This flexibility is not with matrices . use **data.frame()** to construct a data frame from vector.
<br>Most of the data sets are stored in R as data frames. These are like matrices, but with the columns having their own names , Several come with R .
<br>syntax :- $data.frame(New-Name=Old-Name)$

In [120]:
days<- c('Mon', 'Tue', 'Wed', 'Thru', 'Fri')
temp<- c(22, 21, 23, 30, 33)
rain<- c(T, T, F, F, T)
df1<- data.frame(Days=days, Temp=temp, Rain=rain) ; df1

Days Temp Rain 
1 Mon  22    TRUE
2 Tue  21    TRUE
3 Wed  23   FALSE
4 Thru 30   FALSE
5 Fri  33    TRUE

In [121]:
str(df1)  # To see the structure of data / data frame

'data.frame':	5 obs. of  3 variables:
 $ Days: Factor w/ 5 levels "Fri","Mon","Thru",..: 2 4 5 3 1
 $ Temp: num  22 21 23 30 33
 $ Rain: logi  TRUE TRUE FALSE FALSE TRUE


In [122]:
summary(df1)

   Days        Temp         Rain        
 Fri :1   Min.   :21.0   Mode :logical  
 Mon :1   1st Qu.:22.0   FALSE:2        
 Thru:1   Median :23.0   TRUE :3        
 Tue :1   Mean   :25.8                  
 Wed :1   3rd Qu.:30.0                  
          Max.   :33.0                  

In [123]:
df1[1,]  # To extract the data row-wise

Days Temp Rain
1 Mon  22   TRUE

In [124]:
df1['Rain']  # To extract the data by column name

Rain 
1  TRUE
2  TRUE
3 FALSE
4 FALSE
5  TRUE

In [125]:
# Here we extract 1st to 5th row with Days and Temp columns from the data
df1[1:5,c('Days','Temp')]

Days Temp
1 Mon  22  
2 Tue  21  
3 Wed  23  
4 Thru 30  
5 Fri  33

In [126]:
df1$Temp # To extract the data using dollor '$' sign

[1] 22 21 23 30 33

In [127]:
df1['Temp']  #  # To extract the data column name

Temp
1 22  
2 21  
3 23  
4 30  
5 33

In [128]:
# Note :- If we extract the data in using 'dollar' sign then 
# we get the extracted data into row-wise while If we extract the data
# in using ['column_name'] then we get the extracted data into column-wise

# To filter the data --'subset()'
subset(df1, subset = rain==TRUE)  
# It gives the only data when the rain occurs OR rain is TRUE 

Days Temp Rain
1 Mon  22   TRUE
2 Tue  21   TRUE
5 Fri  33   TRUE

In [129]:
#  It gives the only data when the Temperature is greater than 23
subset(df1, subset = temp>23)

Days Temp Rain 
4 Thru 30   FALSE
5 Fri  33    TRUE

In [130]:
# To Short the data
sorted.temp<- order(df1['Temp'])
sorted.temp   # It gives the ascending order according to temperature

[1] 2 1 3 4 5

In [132]:
df1[sorted.temp,] # It gives the data in ordered form (Ascending Order)

Days Temp Rain 
2 Tue  21    TRUE
1 Mon  22    TRUE
3 Wed  23   FALSE
4 Thru 30   FALSE
5 Fri  33    TRUE

In [133]:
# descending order according to temperature
order(-df1['Temp'])

[1] 5 4 3 1 2

In [134]:
# If we want to delete any row from the data 
df1[-2,]

Days Temp Rain 
1 Mon  22    TRUE
3 Wed  23   FALSE
4 Thru 30   FALSE
5 Fri  33    TRUE

In [135]:
# If we want to delete any column from the data 
df1[,-3]

Days Temp
1 Mon  22  
2 Tue  21  
3 Wed  23  
4 Thru 30  
5 Fri  33

# Control Statements
Control statements allows us to control the flow Control statements allow us to control the flow of our programming and cause different things to happen, depending on the values of tests. Tests result in a logical, TRUE or FALSE, which is used in if-like statements. The main control statements are **if, else, ifelse and switch** .
##  if and else --Statement
The most common test is the *if* command. It essentially says. If something is TRUE, then perform some action; otherwise, do not perform that action. The thing we are testing goes inside parentheses following the *if* command. The most basic checks are: equal to (==), less than (<), less than or equal to (<=), greater than (>), greater than or equal to (>=) and not equal (!=).If these tests pass they result in TRUE, and if they fail they result in FALSE.TRUE is numerically equivalent to 1 and FALSE is equivalent to 0.

In [136]:
#  set up a variable to hold 1
toCheck<- 1
# if toCheck is equal to 1, print hello
if(toCheck == 1)
{
  print("Mohammad Wasiq")
}

[1] "Mohammad Wasiq"


In [137]:
#  set up a variable to hold 1
toCheck<- 3
# if toCheck is equal to 1, print hello
if(toCheck == 1)
{
  print("Mohammad Wasiq")
}else
{
  print("Wrong Option")
}

[1] "Wrong Option"


In [138]:
check.book<- function(x)
{
  if(x == 1)
  {
# If the input is equal to 1, print hello
  print("hello")  
  }else if(x == 0)
  {
# If the input equal to 0 , print goodbye    
    print("goodbye")
  }else
  {
# Otherwise print confused
    print("confused")
  }  
}
check.book(1)

[1] "hello"


In [139]:
check.book(0)

[1] "goodbye"


In [140]:
check.book(5)

[1] "confused"


## Switch –Statement
If we have multiple cases to check, writing *else if* repeatedly can be
cumbersome and inefficient. This is where *switch* is most useful. The
first argument is the value we are testing. Subsequent arguments are a
particular value and what should be the result. The last argument, if
not given a value, is the default result .
$$switch (object, case = action)$$

In [141]:
use.switch<- function(x)
{
switch (x,
"a" = "first" ,
"b" = "second" , 
"c" = "third" ,
"d" = "last" ,
"other")
}
use.switch("a")  # use.switch(1)

[1] "first"

In [142]:
use.switch("b")  # use.switch(2)

[1] "second"

In [143]:
use.switch("g")  # use.switch(7)

[1] "other"

## ifelse – Statement
While *if* is like the if statement in traditional languages, *ifelse* is more like the if function in Excel. The first argument is the condition to be tested (much like in a traditional *if* statement), the second argument is the return value if the test is **TRUE** and the third argument is the return value if the test if **FALSE** . The beauty here—unlike with the traditional *if*—is that this works with vectorized arguments. As is often the case in R, using vectorization avoids *for* loops and speeds up our code. The nuances of *ifelse* can be tricky, so we show numerous examples.

In [144]:
# see if 1 == 1
ifelse(1 == 1, "Yes", "No")

[1] "Yes"

In [145]:
# see if 1 == 0
ifelse(1 == 0, "Yes", "No")

[1] "No"

This clearly gives us the results we want. ifelse uses all the regular equality tests and any other logical test. It is worth noting, however, that if testing just a single element (a vector of length 1 or a simple is.na), it is more efficient to use if than ifelse. This can result in a nontrivial speedup of our code.

In [146]:
toTest <- c(1, 1, 0, 1, 0, 1)
ifelse(toTest == 1, "Yes", "No")

[1] "Yes" "Yes" "No"  "Yes" "No"  "Yes"

In [147]:
# This returned “Yes” for each element of toTest that equaled 1 and “No”
# for each element of toTest that did not equal 1. 
ifelse(toTest == 1, toTest*3, toTest)

[1] 3 3 0 3 0 3

In [148]:
# the FALSE argument is repeated as needed
ifelse(toTest == 1, toTest*3, "Zero")

[1] "3"    "3"    "Zero" "3"    "Zero" "3"

In [149]:
#This would be the same if the TRUE and FALSE arguments are vectors.
ifelse(toTest == 1, toTest*3, toTest)

[1] 3 3 0 3 0 3

In [150]:
ifelse(toTest == 1, toTest*3, "Zero")

[1] "3"    "3"    "Zero" "3"    "Zero" "3"

**Conclusion**
<br>Controlling the flow of our program, both at the command line and in functions, plays an important role when processing and analyzing our data. If statements, along with else, are the most common—and efficient—for testing single element objects, although ifelse is far more common in R programming because of its vectorized nature. Switch statements are often forgotten but can come in very handy. The and (& and &&) and or (| and ||) operators allow us to combine multiple tests into one .

## Loops in R 
When starting to use R, most people use loops whenever they need to iterate over elements of a vector, list or data.frame. While it is natural to do this in other languages, with R we generally want to use vectorization. That said, sometimes loops are unavoidable, so R offers both *for* and *while* loops.
### for Loops
**_for (variable in vector) {}_**
<br>The most commonly used loop is the *for* loop. It iterates over an index—provided as a vector—and performs some operations. For a first simple example, we print out the first ten numbers. The loop is declared using *for*, which takes one English-seeming argument in three parts. The third part is any vector of values of any kind, most commonly numeric or character. The first part is the variable that is iteratively assigned the values in the vector from the third part. The middle part is simply the word in indicating that the variable (the first part) is in the vector (the third part).

In [151]:
for(i in 1:10)
    { 
    print(i)
    }

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [152]:
v<- c(1,2,3,4,5,6)
for(temp.var in v){
result<- temp.var+1  
  print("Mohammad Wasiq")
  print(result)
}

[1] "Mohammad Wasiq"
[1] 2
[1] "Mohammad Wasiq"
[1] 3
[1] "Mohammad Wasiq"
[1] 4
[1] "Mohammad Wasiq"
[1] 5
[1] "Mohammad Wasiq"
[1] 6
[1] "Mohammad Wasiq"
[1] 7


### while Loop
Although used far less frequently in R than the *for* loop, the *while* loop is just as simple to implement. Itsimply runs the code inside the braces repeatedly as long as the tested condition proves true. In the following example, we print the value of x and iterate it until it reaches 5. This is a highly trivial example but shows the functionality nonetheless.

In [153]:
x <- 1
while(x <= 5)
{
 print(x)
 x <- x + 1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


### Controlling Loops
Sometimes we have to skip to the next iteration of the loop or completely break out of it. This is accomplished with next and break.

In [154]:
for(i in 1:10)
{
 if(i == 3)
 {
 next
 }
 print(i)
}

[1] 1
[1] 2
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [155]:
# Notice that the number 3 did not get printed.
for(i in 1:10)
{
 if(i == 4)
 {
 break
 }
 print(i)
}

[1] 1
[1] 2
[1] 3


**Conclusion-**    
<br>The two primary loops are for, which iterates over a fixed sequence of elements, and while which continues a loop as long as some condition holds true. As stated earlier, if a solution can be done without loops, via vectorization or matrix algebra, then avoid the loop. It is particularly important to avoid nested loops. Loops inside other loops are extremely slow in R.

# Apply Family
Apply, Sapply, Mapply, Tapply, Rapply, Eapply, Vapply are the members of apply family . Here we ae discussing only three .
## Apply in R
*apply* is the first member of this family that users usually learn, and it is also the most restrictive. It must be used on a matrix, meaning all of the elements must be of the same type whether they are character, numeric or logical. If used on some other object, such as a data.frame, it will be converted to a matrix first. The first argument to *apply* is the object we are working with. The second argument is the margin to apply the function over, 1 meaning to operate over the rows and 2
meaning to operate over the columns. The third argument is the function we want to apply. Any following arguments will be passed on to that function. *apply* will iterate over each row (or column) of the matrix, treating them as individual inputs to the first argument of the
specified function.
$$apply(array, margin, ...)$$

In [156]:
# Build the Matrix
mat<- matrix(1:9 ,nrow=3) ;mat

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [158]:
# Sum the MAtrix rows wise
apply(mat, 1, sum)

[1] 12 15 18

In [159]:
# Sum the Matrix Columns -wise
apply(mat, 2, sum)

[1]  6 15 24

In [160]:
# We Can also find the Sum row-wisw/column-wise of a matrix
rowSums(mat)  # Row-wise Sum

[1] 12 15 18

In [161]:
colSums(mat)  # Column-wise Sum

[1]  6 15 24

## Lapply in R
lapply works by applying a function to each element of a list and returning the results as a list. 
$$lapply(list, function)$$

In [162]:
thelist<- list(A=matrix(1:9, 3), B=1:5, C=matrix(1:4, 2),D=2)
thelist

$A
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$B
[1] 1 2 3 4 5

$C
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$D
[1] 2

In [163]:
lapply(thelist, sum)

$A
[1] 45

$B
[1] 15

$C
[1] 10

$D
[1] 2

## Sapply in R
Dealing with lists can be cumbersome, so to return the result of lapply as a vector instead, use sapply. It is exactly the same as lapply in every other way.
$$sapply(list, function)$$

In [164]:
thelist<- list(A=matrix(1:9, 3), B=1:5, C=matrix(1:4, 2),D=2)
thelist

$A
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

$B
[1] 1 2 3 4 5

$C
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$D
[1] 2

In [165]:
sapply(thelist, sum)

A  B  C  D 
45 15 10  2

## Mapply in R
Perhaps the most-overlooked-when-so-useful member of the *apply* family is *mapply*, which applies a function to each element of multiple lists. Often, when confronted with this scenario, people will resort to using a loop, which is certainly not necessary. 
$$mapply(function, ...)$$

In [166]:
## build two lists
firstList <- list(A=matrix(1:16, 4), B=matrix(1:16, 2), C=1:5)
secondList <- list(A=matrix(1:16, 4), B=matrix(1:16, 8), C=15:1)
# test element-by-element if they are identical
mapply(identical, firstList, secondList)

A     B     C 
 TRUE FALSE FALSE

In [167]:
# build a simple function
# it adds the number of rows (or length) of each corresponding element
simpleFunc <- function(x, y)
 {
 NROW(x) + NROW(y)
  }
# apply the function to the two lists
mapply(simpleFunc, firstList, secondList)

A  B  C 
 8 10 20